services:
  docker-clash:
    build:
      context: .
      args:
        MIHOMO_VERSION: v1.19.28
    image: foliage-sea/docker-clash:local
    container_name: docker-clash
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "27890:7890"
    volumes:
      - docker-clash-data:/data

volumes:
  docker-clash-data:
